# -*- coding: utf-8 -*-
"""predictxgboost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15m5C7fgTTt1VsZEL1AcDpaMrIijN5QOg
"""

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder
import joblib
import warnings; warnings.filterwarnings('ignore')

# ── 1. LOAD ────────────────────────────────────────────
df = pd.read_excel('MCRDataset.xlsx')
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(['RegionName', 'Date']).reset_index(drop=True)

# ── 2. FEATURE ENGINEERING ────────────────────────────
# Time features
df['year']    = df['Date'].dt.year
df['month']   = df['Date'].dt.month
df['quarter'] = df['Date'].dt.quarter
# Months since 1995 (linear time trend)
df['time_idx'] = (df['year'] - 1995) * 12 + df['month']

# Encode region as a number
le = LabelEncoder()
df['region_enc'] = le.fit_transform(df['RegionName'])

# Lag features: previous 1, 3, 6, 12 months per region
for lag in [1, 3, 6, 12]:
    df[f'price_lag_{lag}'] = (
        df.groupby('RegionName')['AveragePrice']
          .shift(lag)
    )

# 12-month rolling average (smooths noise)
df['rolling_avg_12'] = (
    df.groupby('RegionName')['AveragePrice']
      .transform(lambda x: x.rolling(12, min_periods=1).mean().shift(1))
)

# Year-on-year price change (%)
df['yoy_change'] = (
    df.groupby('RegionName')['AveragePrice']
      .pct_change(periods=12)
)

df = df.dropna()  # lag features create NaN for early rows

# ── 3. DEFINE FEATURES & TARGET ───────────────────────
FEATURES = [
    'region_enc', 'year', 'month', 'quarter', 'time_idx',
    'SalesVolume', 'SemiDetachedPrice', 'TerracedPrice',
    'FlatPrice', 'FTBPrice', 'NewPrice', 'OldPrice',
    'NewSalesVolume', 'OldSalesVolume',
    'price_lag_1', 'price_lag_3', 'price_lag_6', 'price_lag_12',
    'rolling_avg_12', 'yoy_change'
]
TARGET = 'AveragePrice'

# ── 4. TIME-SERIES SPLIT (never shuffle!) ─────────────
split_date = '2023-01-01'  # last ~2 years = test
train = df[df['Date'] < split_date]
test  = df[df['Date'] >= split_date]

X_train, y_train = train[FEATURES], train[TARGET]
X_test,  y_test  = test[FEATURES],  test[TARGET]

# ── 5. TRAIN XGBOOST ──────────────────────────────────
model = XGBRegressor(
    n_estimators=1000,       # max trees (early stopping will cut this)
    learning_rate=0.05,      # small = more stable
    max_depth=5,             # tree depth (3-7 is good range)
    subsample=0.8,           # use 80% of rows per tree
    colsample_bytree=0.8,    # use 80% of features per tree
    min_child_weight=3,      # prevents overfitting on small groups
    reg_alpha=0.1,           # L1 regularisation
    reg_lambda=1.0,          # L2 regularisation
    early_stopping_rounds=50,# stop if no improvement after 50 rounds
    eval_metric='rmse',
    random_state=42,
    n_jobs=-1                # use all CPU cores
)

model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=100              # print progress every 100 rounds
)

# ── 6. EVALUATE ───────────────────────────────────────
preds = model.predict(X_test)
mae  = mean_absolute_error(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
mape = np.mean(np.abs((y_test - preds) / y_test)) * 100

print(f"MAE:  £{mae:,.0f}")
print(f"RMSE: £{rmse:,.0f}")
print(f"MAPE: {mape:.1f}%")

# ── 7. SAVE MODEL + ENCODER ───────────────────────────
joblib.dump(model, 'mcr_model.joblib')
joblib.dump(le, 'region_encoder.joblib')
print("Model saved!")

df.to_csv("processed_data.csv", index=False)

import matplotlib.pyplot as plt

plt.plot(y_test.values[:100], label="Actual")
plt.plot(preds[:100], label="Predicted")
plt.legend()
plt.show()